### ISSUE TITLE
Event timeline on indexpagina

### ISSUE THREAD

**Issue by eensander** [Zuyd-Gang/casus-b2d3#14]
On the indexpage, display timeline with events in the current month. 
The leftmost end of the timeline is the first day of the current month, while the rightmost end is the last day of the current month.

When an event-bullet is hovered, a tooltip with some eventinformation will be displayed. When clicked, the visitor will be directed to the detailspage of the event

![V 2 1 homepage2](https://user-images.githubusercontent.com/50321538/73063851-0eab0580-3ea0-11ea-8d00-543967b47bd1.PNG)

**Comment by TimCRN** [comment]
Used concept: https://codepen.io/carrrter/pen/ELLmyX

**Comment by eensander** [comment]
_Issues_: when adding custom (li) items. 

**Normal behaviour with default listitems:**
![afbeelding](https://user-images.githubusercontent.com/50321538/73124058-f2d65b00-3f96-11ea-90d0-ef371b729516.png)

**When dupplicating one item (and multiple items at same date occur):** 
![afbeelding](https://user-images.githubusercontent.com/50321538/73124063-fd90f000-3f96-11ea-860f-ac16015ac2ef.png)

**When the duplicated item is changed in both 'data-date' and value:**
![afbeelding](https://user-images.githubusercontent.com/50321538/73124076-3fba3180-3f97-11ea-8d43-62f2178246ab.png)

**Comment by eensander** [comment]
**Todo**: _left_-most and _right_-most item must be respectively be the first day and the last day of the current year(?)

**Comment by eensander** [comment]
Edited timeline.js, timeline.css and index.cshtml (untested currently in MVC5 - only tested locally). 

![image](https://user-images.githubusercontent.com/50321538/73136804-0db9d580-4052-11ea-99a6-1d74b493606e.png)


**Proposed idea**: display all months of the year, when clicked show events in this month in content.
Otherwise just show events as described/expected

**Comment by TimCRN** [comment]
Issue closed due to successful merge into the dev branch
